title: Open Source for Good
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
timezone: America/Los_Angeles
baseurl: ""
url: "https://localhost:4000/"
permalink: /:title
twitter_username: freeCodeCamp
github_username:  freeCodeCamp

jekyll_get:
  data: team
  json: 'https://api.github.com/repos/freecodecamp/food-bank-app/contributors'
  cache: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  parse_block_html: true
theme: minima
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
lsi: false
safe: false
incremental: false
highlighter: rouge
gist:
  noscript: false
exclude:
  - .gitignore
  - README.md
